syntax = "proto3";

package order;

service OrderService {
  rpc CreateOrder (CreateOrderRequest) returns (OrderResponse);
  rpc GetOrder (GetOrderRequest) returns (OrderResponse);
  rpc ListOrders (ListOrdersRequest) returns (ListOrdersResponse);
  rpc Health (HealthRequest) returns (HealthResponse);
}

message OrderItemInput {
  int32 pid = 1;
  int32 qty = 2;
}

message CreateOrderRequest {
  int32 uid = 1;
  repeated OrderItemInput items = 2;
  string request_id = 3;
}

message GetOrderRequest {
  int32 oid = 1;
}

message ListOrdersRequest {
  int32 uid = 1;
}

message OrderItem {
  int32 pid = 1;
  int32 qty = 2;
  string unit_price = 3;
}

message OrderResponse {
  int32 oid = 1;
  int32 uid = 2;
  string discount = 3;
  string total_amount = 4;
  string created_at = 5;
  repeated OrderItem items = 6;
}

message ListOrdersResponse {
  repeated OrderResponse items = 1;
}

message HealthRequest {}

message HealthResponse {
  string status = 1;
}